const site : string = "http://localhost:3003/";
export const siteConfig = {
    links : {
        signup:site + "auth/signup",
        signin:site+"auth/signin",
        twoauth:site+"auth/twoauth",
        metrics:site + "metric/",
        dashboard:site+"track/",
        profile:site+"auth/user",
        compute:site+"compute/",
        website:site+"web/",

    },
    uz : {
        nowebmes:"Websayt ulanmagan.",
        webcreate:"Websayt qoshish",
        language:"Til",
        metrics:"Ko'rsatkichlar",
        website:"Veb-sayt",
        menu:"Menu",
        system:"Tizim",
        theme:"Ko'rinish",
        dark:"Tun",
        light:'Kun',
        twoauthm:"shu elektron pochtaga bir martalik kod yuborildi. shuni ushbu joyga kiriting.",
        forgot:"Kodni unutdingizmi?",
        username:"Foydalanish ism",
        firstname:"Ism",
        lastname:"Familiya",
        email:"Elektron pochta",
        password:"Kod",
        role:"Ish roli",
        owner:"Xo'jayin",
        manager:"Ish boshqaruvchi",
        dev:"Dasturchi",
        designer:"Dizayner",
        analyst:"Tahlilchi",
        project:"Loyiha",
        work:"Ish",
        team:"Guruh",
        teammember:"Guruh a'zosi",
        issue:"Muammo",
        signup:"Ro'yhatdan o'tish",
        signin:"Tizimga kirish",
        signout:"Tizimdan chiqish",
        twoauth:"2-chi darajali tekshiruv",
        hide:"Kodni berkitish",
        show:"Kodni ko'rsatish",
        dashboard:"Asosiy panel",
        process:"Jarayon",
        docs:"Hujjatlar",
        about:"Haqida",
        error:"Hatolik",
        NotAuthorized:"Sizda Kerakli ruhsat yo'q!",
        Forbidden:"Bu ma'lumot sizga ta'qiqlanadi!",
        NotFound:"Bu ma'lumot tizimda mavjud emas",
        CrashServer:"Tizimda ichki hatolik yuz berdi",
        loading:"Ma'lumotlar yuklanmoqda iltimos kuting...",
        upload:"Tizimga yuklash",
        download:"Yuklab olish",
        schedule:"Reja",
        settings:"Sozlamalar",
        send:"Yuborish",
        sent:"Yuborildi",
        recieve:"Olish",
        recieved:"Olindi",
        invite:"Taklif qilish",
        share:"Ulashish",
        comment:"fikr bildirish",
        commented:"fikr bildirildi",
        reply:"Javob qaytarish",
        replied:"Javob qaytarildi",
        accept:"Qabul qilish",
        accepted:"Qabul qilindi",
        cause:"Sabab",
        busy:"Band",
        sick:"Kasal",
        other:"Boshqa",
        options:"Tanlovlar",
        level:"Daraja",
        low:"Past",
        medium:"O'rtacha",
        high:"Baland",
        discuss:"Muhokama",
        start:"Boshlash",
        started:"Boshlandi",
        delete:"O'chirish",
        deleted:"O'chirildi",
        update:"Yangilash",
        updated:"Yangilandi",
        edit:"O'zgartirish",
        edited:"O'zgartirildi",
        status:"Holati",
        reject:"Rad etish",
        rejected:"Rad etildi",
    },
    en : {
        nowebmes:"No website added.",
        webcreate:"Add website",
        language:"Language",
        metrics:"Metrics",
        website:"Website",
        menu:"Menu",
        system:"System",
        theme:"Theme",
        dark:"Dark",
        light:"Light",
        twoauthm:"we have sent 1 time code to this address. Please paste that code in here.",
        forgot:"Forgot password?",
        username:"Username",
        firstname:"Firstname",
        lastname:"Lastname",
        email:"Email",
        password:"Password",
        role:"Role",
        owner:"Owner",
        manager:"Manager",
        dev:"Developer",
        designer:"Designer",
        analyst:"Analyst",
        project:"Projects",
        work:"Work",
        team:"Team",
        teammember:"Team member",
        issue:"Issue",
        signup:"Sign up",
        signin:"Sign in",
        signout:"Sign out",
        twoauth:"Two factor authentication",
        hide:"Hide password",
        show:"Show password",
        dashboard:"Dashboard",
        process:"Process",
        docs:"Documentation",
        about:"About",
        error:"Error",
        NotAuthorized:"You are not Authorized!",
        Forbidden:"It is Forbidden for you!",
        NotFound:"Sorry, it is not available",
        CrashServer:"Sorry, internal server error happened.",
        loading:"It is loading please wait...",
        upload:"Upload",
        download:"Download",
        schedule:"Schedule",
        settings:"Settings",
        send:"Send",
        sent:"Sent",
        recieve:"Receive",
        recieved:"Received.",
        invite:"Invite",
        share:"Share",
        comment:"Comment",
        commented:"Commented.",
        reply:"Reply",
        replied:"Replied.",
        accept:"Accept",
        accepted:"Accepted.",
        cause:"Cause",
        busy:"Busy",
        sick:"Ill",
        other:"Other",
        options:"Options",
        level:"Level",
        low:"Low",
        medium:"Medium",
        high:"High",
        discuss:"Discussion",
        discussion:"Discussion",
        start:"Start",
        started:"Started.",
        delete:"Delete",
        deleted:"Deleted.",
        update:"Update",
        updated:"Updated.",
        edit:"Edit",
        edited:"Edited.",
        status:"Status",
        reject:"Reject",
        rejected:"Rejected.",
    },
    
}